/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GrowRouteImport } from './routes/grow'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as ReportTokenRouteImport } from './routes/report/$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSeoAuditRouteImport } from './routes/_authenticated/seo-audit'
import { Route as AuthenticatedScheduledRouteImport } from './routes/_authenticated/scheduled'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedEngagementRouteImport } from './routes/_authenticated/engagement'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBacklinksRouteImport } from './routes/_authenticated/backlinks'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as ApiPublicSyncSemrushRouteImport } from './routes/api/public/sync-semrush'
import { Route as ApiPublicSyncGscRouteImport } from './routes/api/public/sync-gsc'
import { Route as ApiPublicRunScheduledRouteImport } from './routes/api/public/run-scheduled'
import { Route as ApiPublicQueueDirectoriesRouteImport } from './routes/api/public/queue-directories'
import { Route as ApiPublicOauthShopifyCallbackRouteImport } from './routes/api/public/oauth/shopify/callback'
import { Route as ApiPublicOauthGscCallbackRouteImport } from './routes/api/public/oauth/gsc/callback'
import { Route as ApiPublicOauthGithubCallbackRouteImport } from './routes/api/public/oauth/github/callback'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowRoute = GrowRouteImport.update({
  id: '/grow',
  path: '/grow',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const ReportTokenRoute = ReportTokenRouteImport.update({
  id: '/report/$token',
  path: '/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeoAuditRoute = AuthenticatedSeoAuditRouteImport.update({
  id: '/seo-audit',
  path: '/seo-audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduledRoute = AuthenticatedScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngagementRoute = AuthenticatedEngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBacklinksRoute = AuthenticatedBacklinksRouteImport.update({
  id: '/backlinks',
  path: '/backlinks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSyncSemrushRoute = ApiPublicSyncSemrushRouteImport.update({
  id: '/api/public/sync-semrush',
  path: '/api/public/sync-semrush',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncGscRoute = ApiPublicSyncGscRouteImport.update({
  id: '/api/public/sync-gsc',
  path: '/api/public/sync-gsc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunScheduledRoute = ApiPublicRunScheduledRouteImport.update({
  id: '/api/public/run-scheduled',
  path: '/api/public/run-scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQueueDirectoriesRoute =
  ApiPublicQueueDirectoriesRouteImport.update({
    id: '/api/public/queue-directories',
    path: '/api/public/queue-directories',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthShopifyCallbackRoute =
  ApiPublicOauthShopifyCallbackRouteImport.update({
    id: '/api/public/oauth/shopify/callback',
    path: '/api/public/oauth/shopify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthGscCallbackRoute =
  ApiPublicOauthGscCallbackRouteImport.update({
    id: '/api/public/oauth/gsc/callback',
    path: '/api/public/oauth/gsc/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthGithubCallbackRoute =
  ApiPublicOauthGithubCallbackRouteImport.update({
    id: '/api/public/oauth/github/callback',
    path: '/api/public/oauth/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/data-deletion': typeof DataDeletionRoute
  '/grow': typeof GrowRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/backlinks': typeof AuthenticatedBacklinksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/engagement': typeof AuthenticatedEngagementRoute
  '/media': typeof AuthenticatedMediaRoute
  '/scheduled': typeof AuthenticatedScheduledRoute
  '/seo-audit': typeof AuthenticatedSeoAuditRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/report/$token': typeof ReportTokenRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/api/public/queue-directories': typeof ApiPublicQueueDirectoriesRoute
  '/api/public/run-scheduled': typeof ApiPublicRunScheduledRoute
  '/api/public/sync-gsc': typeof ApiPublicSyncGscRoute
  '/api/public/sync-semrush': typeof ApiPublicSyncSemrushRoute
  '/api/public/oauth/github/callback': typeof ApiPublicOauthGithubCallbackRoute
  '/api/public/oauth/gsc/callback': typeof ApiPublicOauthGscCallbackRoute
  '/api/public/oauth/shopify/callback': typeof ApiPublicOauthShopifyCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/data-deletion': typeof DataDeletionRoute
  '/grow': typeof GrowRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/backlinks': typeof AuthenticatedBacklinksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/engagement': typeof AuthenticatedEngagementRoute
  '/media': typeof AuthenticatedMediaRoute
  '/scheduled': typeof AuthenticatedScheduledRoute
  '/seo-audit': typeof AuthenticatedSeoAuditRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/report/$token': typeof ReportTokenRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/api/public/queue-directories': typeof ApiPublicQueueDirectoriesRoute
  '/api/public/run-scheduled': typeof ApiPublicRunScheduledRoute
  '/api/public/sync-gsc': typeof ApiPublicSyncGscRoute
  '/api/public/sync-semrush': typeof ApiPublicSyncSemrushRoute
  '/api/public/oauth/github/callback': typeof ApiPublicOauthGithubCallbackRoute
  '/api/public/oauth/gsc/callback': typeof ApiPublicOauthGscCallbackRoute
  '/api/public/oauth/shopify/callback': typeof ApiPublicOauthShopifyCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/data-deletion': typeof DataDeletionRoute
  '/grow': typeof GrowRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/backlinks': typeof AuthenticatedBacklinksRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/engagement': typeof AuthenticatedEngagementRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/scheduled': typeof AuthenticatedScheduledRoute
  '/_authenticated/seo-audit': typeof AuthenticatedSeoAuditRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/report/$token': typeof ReportTokenRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/api/public/queue-directories': typeof ApiPublicQueueDirectoriesRoute
  '/api/public/run-scheduled': typeof ApiPublicRunScheduledRoute
  '/api/public/sync-gsc': typeof ApiPublicSyncGscRoute
  '/api/public/sync-semrush': typeof ApiPublicSyncSemrushRoute
  '/api/public/oauth/github/callback': typeof ApiPublicOauthGithubCallbackRoute
  '/api/public/oauth/gsc/callback': typeof ApiPublicOauthGscCallbackRoute
  '/api/public/oauth/shopify/callback': typeof ApiPublicOauthShopifyCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/data-deletion'
    | '/grow'
    | '/how-it-works'
    | '/privacy'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/accounts'
    | '/analytics'
    | '/backlinks'
    | '/dashboard'
    | '/engagement'
    | '/media'
    | '/scheduled'
    | '/seo-audit'
    | '/settings'
    | '/report/$token'
    | '/resources/$slug'
    | '/api/public/queue-directories'
    | '/api/public/run-scheduled'
    | '/api/public/sync-gsc'
    | '/api/public/sync-semrush'
    | '/api/public/oauth/github/callback'
    | '/api/public/oauth/gsc/callback'
    | '/api/public/oauth/shopify/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/data-deletion'
    | '/grow'
    | '/how-it-works'
    | '/privacy'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/accounts'
    | '/analytics'
    | '/backlinks'
    | '/dashboard'
    | '/engagement'
    | '/media'
    | '/scheduled'
    | '/seo-audit'
    | '/settings'
    | '/report/$token'
    | '/resources/$slug'
    | '/api/public/queue-directories'
    | '/api/public/run-scheduled'
    | '/api/public/sync-gsc'
    | '/api/public/sync-semrush'
    | '/api/public/oauth/github/callback'
    | '/api/public/oauth/gsc/callback'
    | '/api/public/oauth/shopify/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/data-deletion'
    | '/grow'
    | '/how-it-works'
    | '/privacy'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/accounts'
    | '/_authenticated/analytics'
    | '/_authenticated/backlinks'
    | '/_authenticated/dashboard'
    | '/_authenticated/engagement'
    | '/_authenticated/media'
    | '/_authenticated/scheduled'
    | '/_authenticated/seo-audit'
    | '/_authenticated/settings'
    | '/report/$token'
    | '/resources/$slug'
    | '/api/public/queue-directories'
    | '/api/public/run-scheduled'
    | '/api/public/sync-gsc'
    | '/api/public/sync-semrush'
    | '/api/public/oauth/github/callback'
    | '/api/public/oauth/gsc/callback'
    | '/api/public/oauth/shopify/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DataDeletionRoute: typeof DataDeletionRoute
  GrowRoute: typeof GrowRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ReportTokenRoute: typeof ReportTokenRoute
  ApiPublicQueueDirectoriesRoute: typeof ApiPublicQueueDirectoriesRoute
  ApiPublicRunScheduledRoute: typeof ApiPublicRunScheduledRoute
  ApiPublicSyncGscRoute: typeof ApiPublicSyncGscRoute
  ApiPublicSyncSemrushRoute: typeof ApiPublicSyncSemrushRoute
  ApiPublicOauthGithubCallbackRoute: typeof ApiPublicOauthGithubCallbackRoute
  ApiPublicOauthGscCallbackRoute: typeof ApiPublicOauthGscCallbackRoute
  ApiPublicOauthShopifyCallbackRoute: typeof ApiPublicOauthShopifyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grow': {
      id: '/grow'
      path: '/grow'
      fullPath: '/grow'
      preLoaderRoute: typeof GrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/report/$token': {
      id: '/report/$token'
      path: '/report/$token'
      fullPath: '/report/$token'
      preLoaderRoute: typeof ReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seo-audit': {
      id: '/_authenticated/seo-audit'
      path: '/seo-audit'
      fullPath: '/seo-audit'
      preLoaderRoute: typeof AuthenticatedSeoAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduled': {
      id: '/_authenticated/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof AuthenticatedScheduledRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engagement': {
      id: '/_authenticated/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof AuthenticatedEngagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backlinks': {
      id: '/_authenticated/backlinks'
      path: '/backlinks'
      fullPath: '/backlinks'
      preLoaderRoute: typeof AuthenticatedBacklinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sync-semrush': {
      id: '/api/public/sync-semrush'
      path: '/api/public/sync-semrush'
      fullPath: '/api/public/sync-semrush'
      preLoaderRoute: typeof ApiPublicSyncSemrushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-gsc': {
      id: '/api/public/sync-gsc'
      path: '/api/public/sync-gsc'
      fullPath: '/api/public/sync-gsc'
      preLoaderRoute: typeof ApiPublicSyncGscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-scheduled': {
      id: '/api/public/run-scheduled'
      path: '/api/public/run-scheduled'
      fullPath: '/api/public/run-scheduled'
      preLoaderRoute: typeof ApiPublicRunScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/queue-directories': {
      id: '/api/public/queue-directories'
      path: '/api/public/queue-directories'
      fullPath: '/api/public/queue-directories'
      preLoaderRoute: typeof ApiPublicQueueDirectoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/shopify/callback': {
      id: '/api/public/oauth/shopify/callback'
      path: '/api/public/oauth/shopify/callback'
      fullPath: '/api/public/oauth/shopify/callback'
      preLoaderRoute: typeof ApiPublicOauthShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/gsc/callback': {
      id: '/api/public/oauth/gsc/callback'
      path: '/api/public/oauth/gsc/callback'
      fullPath: '/api/public/oauth/gsc/callback'
      preLoaderRoute: typeof ApiPublicOauthGscCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/github/callback': {
      id: '/api/public/oauth/github/callback'
      path: '/api/public/oauth/github/callback'
      fullPath: '/api/public/oauth/github/callback'
      preLoaderRoute: typeof ApiPublicOauthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBacklinksRoute: typeof AuthenticatedBacklinksRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEngagementRoute: typeof AuthenticatedEngagementRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedScheduledRoute: typeof AuthenticatedScheduledRoute
  AuthenticatedSeoAuditRoute: typeof AuthenticatedSeoAuditRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBacklinksRoute: AuthenticatedBacklinksRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEngagementRoute: AuthenticatedEngagementRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedScheduledRoute: AuthenticatedScheduledRoute,
  AuthenticatedSeoAuditRoute: AuthenticatedSeoAuditRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DataDeletionRoute: DataDeletionRoute,
  GrowRoute: GrowRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ReportTokenRoute: ReportTokenRoute,
  ApiPublicQueueDirectoriesRoute: ApiPublicQueueDirectoriesRoute,
  ApiPublicRunScheduledRoute: ApiPublicRunScheduledRoute,
  ApiPublicSyncGscRoute: ApiPublicSyncGscRoute,
  ApiPublicSyncSemrushRoute: ApiPublicSyncSemrushRoute,
  ApiPublicOauthGithubCallbackRoute: ApiPublicOauthGithubCallbackRoute,
  ApiPublicOauthGscCallbackRoute: ApiPublicOauthGscCallbackRoute,
  ApiPublicOauthShopifyCallbackRoute: ApiPublicOauthShopifyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
